<a href="https://colab.research.google.com/github/AS0728/com2022/blob/main/%EC%8B%A4%EC%8A%B5Zero.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. 파이썬 기초(Optional)
### 프린트
$ y= x+1 $

In [ ]:
print("Hello world")

#integer
x = 3
print("정수: %01d, %02d, %03d" %(x,x,x))

#float
x = 256.123
print("실수: %.0f, %.1f, %.2f" %(x,x,x))

#string
x = "Hello, world"
print("문자열: [%s]" %(x))

Hello world
정수: 3, 03, 003
실수: 256, 256.1, 256.12
문자열: [Hello, world]


### 반복문, 조건문

In [ ]:
contents = ["Regression", "Classification", "SYM", "Cluetering" , "Dimension reduction", "NN", "CNN", "AE", "GAN", "RNN"]

for con in contents:
  if con in ["Regression", "Classification", "SYM", "Cluetering" , "Dimension reduction"]:
    print ("%s 은(는) 기계학습 내용입니다." %con)
  elif con in ["CNN"]:
    print ("%s 은(는) convolutional neural network 입니다." %con)
  else:
    print ("%s은(는) 심층학습 내용입니다." %con)

Regression 은(는) 기계학습 내용입니다.
Classification 은(는) 기계학습 내용입니다.
SYM 은(는) 기계학습 내용입니다.
Cluetering 은(는) 기계학습 내용입니다.
Dimension reduction 은(는) 기계학습 내용입니다.
NN은(는) 심층학습 내용입니다.
CNN 은(는) convolutional neural network 입니다.
AE은(는) 심층학습 내용입니다.
GAN은(는) 심층학습 내용입니다.
RNN은(는) 심층학습 내용입니다.


### 반복문과 인덱스

In [ ]:
for (i,con) in enumerate(contents):
  print ("[%d/%d]: %s" %(i, len(contents), con))

[0/10]: Regression
[1/10]: Classification
[2/10]: SYM
[3/10]: Cluetering
[4/10]: Dimension reduction
[5/10]: NN
[6/10]: CNN
[7/10]: AE
[8/10]: GAN
[9/10]: RNN


### 함수

In [ ]:
def sum(a,b):
  return a+b

x = 10.0
y = 20.0
print ("%.1f + %.1f = %.1f" %(x, y, sum(x,y)))

10.0 + 20.0 = 30.0


### 리스트

In [ ]:
a = []
b = [1,2,3]
c = ["Hello", ",", "world"]
d = [1,2,3,"x", "y", "z"]
x=[]
print (x)

x.append('a')
print (x)

x.append(123)
print (x)

x.append(["a", "b"])
print(x)

[]
['a']
['a', 123]
['a', 123, ['a', 'b']]


### 딕셔너리(dictionary)

In [ ]:
dic = dict()
dic["name"] = "Heekyung"
dic["town"] = "Goyang city"
dic["job"] = "Assistent professor"
print (dic)

{'name': 'Heekyung', 'town': 'Goyang city', 'job': 'Assistent professor'}


### 클래스

In [ ]:
class Student:
  #생성자
  def __init__(self, name):
    self.name = name
  #메써드
  def study(self, hard=False):
    if hard:
      print("%s 학생은 열심히 공부합니다." %self.name)
    else:
      print ("%s 학생은 공부합니다." %self.name)

s = Student('Heekyung')
s.study()
s.study(hard=True)

Heekyung 학생은 공부합니다.
Heekyung 학생은 열심히 공부합니다.


###라이브러리(패키지) 로드###

In [ ]:
import numpy as np

##**2. 벡터, 행렬 연상, 그래프 그리기** ##

###프린트###

In [ ]:
def print_val (x) :
  print("Type:", type(x))
  print("Shape:", x.shape)
  print("값:\n", x)
  print("")

###rank 1 np array###

In [ ]:
x = np.array([1,2,3])
print_val (x)

x[0] = 5
print_val(x)

Type: <class 'numpy.ndarray'>
Shape: (3,)
값:
 [1 2 3]

Type: <class 'numpy.ndarray'>
Shape: (3,)
값:
 [5 2 3]



###rank 2 np array###

In [ ]:
y = np.array([[1,2,3], [4,5,6]])
print_val (y)

Type: <class 'numpy.ndarray'>
Shape: (2, 3)
값:
 [[1 2 3]
 [4 5 6]]



###rank 2 zeros###

In [ ]:
a = np.zeros((2,2))
print_val (a)

Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값:
 [[0. 0.]
 [0. 0.]]



###rank 2 ones###

In [ ]:
a = np.ones((3,2))
print_val (a)

Type: <class 'numpy.ndarray'>
Shape: (3, 2)
값:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]



###rank 2 단위 행렬(identity matrix)###

In [ ]:
a = np.eye(3,3)
print_val (a)

Type: <class 'numpy.ndarray'>
Shape: (3, 3)
값:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



###랜덤 행렬(uniform: 0~1 사이 모든 값들이 나올 확률이 같음)###

In [ ]:
a = np.random.random((4,4))
print_val (a)

Type: <class 'numpy.ndarray'>
Shape: (4, 4)
값:
 [[0.57632032 0.19874418 0.16217389 0.96334552]
 [0.6097467  0.94049993 0.84156507 0.67592919]
 [0.24404053 0.2306522  0.13698079 0.55745737]
 [0.30776779 0.31249677 0.98521339 0.38963415]]



###랜덤 행렬(Gaussian: 0을 평균으로 하는 가우시안 분포를 따르는 랜덤값)###

In [ ]:
a = np.random.randn(4,4)
print_val (a)

Type: <class 'numpy.ndarray'>
Shape: (4, 4)
값:
 [[-0.14604166 -1.58191451  0.1949468   1.56926054]
 [ 0.46301576  0.28170539  0.4557184   0.62070783]
 [ 1.5075735   0.25419835 -1.54916834  0.72996287]
 [ 0.39934579  0.39130603 -0.56343958 -1.56037193]]



###np array indexing###

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print_val (a)

Type: <class 'numpy.ndarray'>
Shape: (3, 4)
값:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]



In [ ]:
b = a[:2, 1:3]
print_val (b)

Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값:
 [[2 3]
 [6 7]]



###행렬의 n번째 행 얻기###

In [ ]:
row1 = a[1,:]
print_val(row1)

Type: <class 'numpy.ndarray'>
Shape: (4,)
값:
 [5 6 7 8]



###행렬의 원소별 연산###

In [ ]:
m1 = np.array([[1,2], [3,4]], dtype=np.float64)
m2 = np.array([[5,6], [7,8]], dtype=np.float64)

print_val (m1+m2)
print_val(np.add(m1, m2))

Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값:
 [[ 6.  8.]
 [10. 12.]]

Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값:
 [[ 6.  8.]
 [10. 12.]]

